---
title: "Changes in land use associated with increasing woody cover across the Eastern United States"
author: "Michaella A. Ivey^1^, Noah C. Weidig^1^, Alan Ivory^1^, Victoria M. Donovan^1^"
date: "2024-07-31"
output: pdf_document
header-includes:
  - \usepackage{pdflscape}
---

\textsuperscript{1}University of Florida, School of Forest, Fisheries, and Geomatics Sciences, West Florida Research and Education Center, Institute of Food and Agricultural Sciences, University of Florida, Milton, FL, USA

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
pacman::p_load(tidyverse, skimr, flextable, trend, sf, cowplot, colorspace, data.table, officer, snakecase)
set_flextable_defaults(font.family = "Times New Roman", line.spacing = 1)

land_cover_classes <-
  tribble(~combined_code, ~class_name,
          11, "Open Water",
          12, "Perennial Ice Snow",
          21, "Developed Open Space",
          22, "Developed Low Intensity",
          23, "Developed Medium Intensity",
          24, "Developed High Intensity",
          31, "Barren Land",
          41, "Deciduous Forest",
          42, "Evergreen Forest",
          43, "Mixed Forest",
          51, "Dwarf Scrub",
          52, "Shrub/Scrub",
          71, "Grassland/Herbaceous",
          72, "Sedge Herbaceous",
          73, "Lichens",
          74, "Moss",
          81, "Pasture/Hay",
          82, "Cultivated Crops",
          90, "Woody Wetlands",
          95, "Emergent Herbaceous Wetlands")

ecoregion_names <- fread("data/us_l3code_to_ecoregion_name.csv")
```

```{r import_data_21}
area_21 <- fread("data/nlcd_rap_data/nlcd_area_2021.csv")
file_path_21 <- "data/nlcd_rap_data/"
file_names_21 <- paste0("nlcd_rap_2021_", 2001:2021, ".csv")

all_data_21 <- file_names_21 %>%
  map_dfr(~ fread(file.path(file_path_21, .))) %>%
  rename(poly_id = index)

merged_21 <- all_data_21 %>%
  left_join(area_21, by = c("us_l3code", "poly_id", "combined_code")) %>%
  mutate(area_wc = mean * area_ha) %>%
  left_join(land_cover_classes, by = "combined_code") %>%
  filter(!class_name %in% c("Barren Land", "Open Water")) %>%
  mutate(class_name = ifelse(str_detect(class_name,
                                      regex("developed", ignore_case = TRUE)), 
                           "Developed", class_name)) %>%
  group_by(class_name, us_l3code, year) %>%
  summarise(area_wc = sum(area_wc), area_ha = sum(area_ha), .groups = "drop") %>%
  rename(class_21 = class_name) %>%
  left_join(ecoregion_names, by = "us_l3code") %>%
  write_csv("outputs/woody_cover_change_eco_all.csv")

sen_data_21 <- merged_21 %>%
  group_by(class_21, year) %>%
  summarise(area_wc = as.numeric(sum(area_wc)),
            area_ha = as.numeric(sum(area_ha)), .groups = "drop") %>%
  mutate(perc_wc = (area_wc / area_ha) * 100) %>%
  select(class_21, year, perc_wc, area_wc) %>%
  arrange(class_21, year)

sens_results_21 <- sen_data_21 %>%
  group_by(class_21) %>%
  summarise(perc_wc_slope = sens.slope(perc_wc)$estimates,
            perc_wc_p_value = sens.slope(perc_wc)$p.value,
            area_wc_slope = sens.slope(area_wc)$estimates,
            area_wc_p_value = sens.slope(area_wc)$p.value) %>%
  mutate(across(where(is.numeric), ~ round(., 3)),
         mutate(across(matches("p_value$"), ~ ifelse(. < 0.001, "<0.001", .))))

lc_change_21 <- merged_21 %>%
  filter(year %in% c(2001, 2021)) %>%
  group_by(class_21, year) %>%
  summarise(area_wc = sum(area_wc),
            area_ha = sum(area_ha), .groups = 'drop') %>%
  mutate(perc_wc = (area_wc / area_ha) * 100) %>%
  pivot_wider(names_from = year,
              values_from = c(area_wc, area_ha, perc_wc)) %>%
  mutate(area_change = (area_wc_2021 - area_wc_2001),
         perc_change = (perc_wc_2021 - perc_wc_2001),
         perc_area_change = (area_change / area_wc_2001) * 100) %>%
  left_join(sens_results_21, by = "class_21") %>%
  select(class_21, area_ha_2021,
         area_wc_2001, perc_wc_2001,
         area_wc_2021, perc_wc_2021,
         area_change, perc_area_change,
         perc_wc_slope, perc_wc_p_value) %>%
  mutate(across(where(is.numeric),
                ~ case_when(. >= 100 ~ round(., 0),
                            . < 100 & . > 1 ~ round(., 1),
                            . <= 1 & . >= -1 ~ round(., 3),
                            TRUE ~ round(., 0)))) %>%
  write_csv("outputs/data/nlcd_rap_totals_ft_l1.csv")
```

```{r l3_change}
merged_21_l3 <- all_data_21 %>%
  left_join(area_21, by = c("us_l3code", "poly_id", "combined_code")) %>%
  mutate(area_wc = mean * area_ha) %>%
  left_join(ecoregion_names, by = "us_l3code") %>%
  left_join(land_cover_classes, by = "combined_code") %>%
  filter(!class_name %in% c("Barren Land", "Open Water")) %>%
  mutate(class_name = ifelse(str_detect(class_name,
                                      regex("developed", ignore_case = TRUE)), 
                           "Developed", class_name)) %>%
  group_by(class_name, us_l3name, year) %>%
  summarise(area_wc = sum(area_wc), area_ha = sum(area_ha), .groups = "drop") %>%
  rename(class_21 = class_name)

sen_data_21_l3 <- merged_21_l3 %>%
  group_by(class_21, year, us_l3name) %>%
  summarise(area_wc = as.numeric(sum(area_wc)),
            area_ha = as.numeric(sum(area_ha)), .groups = "drop") %>%
  mutate(perc_wc = (area_wc / area_ha) * 100) %>%
  select(us_l3name, class_21, year, perc_wc, area_wc) %>%
  arrange(us_l3name,class_21, year)


# Calculate Sen's slope and p-value for both `perc_wc` and `area_wc`
sens_results_21_l3 <- sen_data_21_l3 %>%
  group_by(class_21, us_l3name) %>%
  summarise(perc_wc_slope = sens.slope(perc_wc)$estimates,
            perc_wc_p_value = sens.slope(perc_wc)$p.value,
            area_wc_slope = sens.slope(area_wc)$estimates,
            area_wc_p_value = sens.slope(area_wc)$p.value, .groups = "drop") %>%
  mutate(across(where(is.numeric), ~ round(., 3)),
         mutate(across(matches("p_value$"), ~ ifelse(. < 0.001, "<0.001", .))))

# Summarize for both years in one step
lc_change_21_l3 <- merged_21_l3 %>%
  filter(year %in% c(2001, 2021)) %>%
  group_by(us_l3name, class_21, year) %>%
  summarise(area_wc = sum(area_wc), area_ha = sum(area_ha), .groups = 'drop') %>%
  mutate(perc_wc = (area_wc / area_ha) * 100) %>%
  pivot_wider(names_from = year, values_from = c(area_wc, area_ha, perc_wc)) %>%
  mutate(area_change = (area_wc_2021 - area_wc_2001),
         perc_change = (perc_wc_2021 - perc_wc_2001),
         perc_area_change = (area_change / area_wc_2001) * 100) %>%
  left_join(sens_results_21_l3, by = c("class_21", "us_l3name")) %>%
  select(us_l3name, class_21, area_ha_2021,
         area_wc_2001, perc_wc_2001,
         area_wc_2021, perc_wc_2021,
         area_change, perc_area_change,
         perc_wc_slope, perc_wc_p_value) %>%
  mutate(across(where(is.numeric),
                ~ case_when(. >= 100 ~ round(., 0),
                            . < 100 & . > 1 ~ round(., 1),
                            . <= 1 & . >= -1 ~ round(., 3),
                            TRUE ~ round(., 0)))) %>%
  write_csv("outputs/data/nlcd_rap_totals_ft_l3.csv")
```

```{r objective_1_figure}
l3_eco_shp <- st_read("~/OneDrive - University of Florida/thesis/data/us_eco_l3/us_eco_l3.shp", quiet = TRUE) %>%
  filter(NA_L1CODE == 8) %>%
  dplyr::select(us_l3name = NA_L3NAME) %>%
  group_by(us_l3name) %>%
  summarise()

library(ggspatial)

scale_params <- tibble(facet_var = "Deciduous Forest", width_hint = 0.25,
                 style = "bar", location = "bl",
                 unit_category = "metric", text_col = "black",
                 line_col = "black")

# Merge change data with eco-region data and classify significance
lc_change_l3_shp <- lc_change_21_l3 %>%
  merge(l3_eco_shp, by = "us_l3name") %>%
  mutate(sig = ifelse(perc_wc_p_value > 0.05, "non_sig", "sig"))

perc_plot <- 
  lc_change_l3_shp %>%
  filter(class_21 != "Cultivated Crops") %>%
  ggplot() +
  geom_sf(aes(geometry = geometry,
              fill = ifelse(sig == "non_sig", NA, perc_wc_slope),
              color = "")) +
  geom_text(aes(label = str_wrap(class_21, 20)), size = 4,
                x = 1000000, y = 2900000) +
  scale_fill_steps2(low = "#0072B2",
                    mid = "white",
                    high = "#D0B903",
                    midpoint = 0,
                    na.value = "grey",
                    name = "Sen's Slope\n(%/year)",
                    n.breaks = 8, nice.breaks = TRUE, show.limits = F) +
  theme_void() +
  theme(legend.position = "bottom",
        strip.text = element_blank(),
        strip.background = element_blank(),
        panel.spacing.x = unit(-1, "lines"),
        panel.spacing.y = unit(0.5, "lines")) +
  scale_color_manual(values  = NA, labels = "n.s.") +
  guides(fill  = guide_colorsteps(order = 1,
                                  even.steps = TRUE,
                                  keywidth = unit(6, "cm")),
         color = guide_legend("", override.aes = list(color = "grey",
                                                      fill = "grey"),
                              order = 2)) +
  annotation_scale(location = "bl", line_width = unit(0.3, "cm"),
                   height = unit(0.1, "cm"), plot_unit = "m",
                   data = subset(lc_change_l3_shp,
                                 class_21 == "Woody Wetlands")) +
  annotation_north_arrow(style = north_arrow_minimal(),
                         location = "br",
                         height = unit(0.7, "cm"),
                         width = unit(0.5, "cm"),
                         data = subset(lc_change_l3_shp,
                                       class_21 == "Woody Wetlands")) +
   facet_wrap(~class_21)

# Save the combined plot
ragg::agg_png(filename = "outputs/objective_1/objective_1_fig.png", scaling = 0.6,
              height = 5, width = 4, units = "in", res = 600)
print(perc_plot)
invisible(dev.off())

crops_plot <- 
  lc_change_l3_shp %>%
  filter(class_21 == "Cultivated Crops") %>%
  ggplot() +
  geom_sf(aes(geometry = geometry,
              fill = ifelse(sig == "non_sig", NA, perc_wc_slope),
              color = "")) +
  scale_fill_steps2(low = "#0072B2",
                    mid = "white",
                    high = "#D0B903",
                    midpoint = 0,
                    na.value = "grey",
                    name = "Sen's Slope\n(%/year)",
                    n.breaks = 8, nice.breaks = TRUE, show.limits = F) +
  theme_minimal() +
  theme(axis.text = element_blank(),
        panel.grid = element_blank(),
        legend.position = "bottom",
        strip.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold")) +
  scale_color_manual(values  = NA, labels = "n.s.") +
  guides(fill  = guide_colorsteps(order = 1,
                                  even.steps = TRUE,
                                  keywidth = unit(6, "cm")),
         color = guide_legend("", override.aes = list(color = "grey", fill = "grey"),
                              order = 2)) +
  annotation_scale(location = "bl", line_width = unit(0.3, "cm"),
                   height = unit(0.2, "cm"), plot_unit = "m") +
  annotation_north_arrow(style = north_arrow_minimal(),
                         location = "br",
                         height = unit(0.7, "cm"),
                         width = unit(0.5, "cm"))

# Save the combined plot
ragg::agg_png(filename = "outputs/objective_1/objective_1_crops_fig.png", scaling = 0.6,
              height = 4, width = 3, units = "in", res = 600)
print(crops_plot)
invisible(dev.off())
```

```{r line_graphs}
# Area over time
plots <-
  merged_21_l3 %>%
  left_join(sens_results_21_l3, by = c("us_l3name", "class_21")) %>%
  mutate(label = paste("Sens Slope:", round(area_wc_slope, 2),
                        "\nP-value:", area_wc_p_value)) %>%
  arrange(us_l3name) %>%
  group_by(us_l3name) %>%
  group_split() %>%
  set_names(map(., ~ unique(.x$us_l3name))) %>%
  map(~ ggplot(.x, aes(x = year, y = area_wc)) +
        geom_line() +
        geom_smooth(se = TRUE, method = "loess", formula = 'y ~ x') +
        geom_text(data = .x %>% group_by(class_21) %>% 
                    summarize(x_pos = min(year), 
                              y_pos = max(area_wc), 
                              label = first(label), 
                              .groups = "drop"), 
                  aes(x = x_pos, y = y_pos, label = label), 
                  inherit.aes = FALSE, 
                  hjust = 0, vjust = 1, size = 3) +
        facet_wrap(~ class_21, scales = "free") +
        labs(x = "Year",
             y = "Area of woody cover (ha)",
             title = unique(.x$us_l3name)) +
        theme_minimal() +
        theme(legend.position = "bottom"))

plots %>%
  imap(~ ggsave(filename = paste0(str_replace_all(to_snake_case(.y),
                                                  "[ /]", "_"),
                                  "_area_change.jpg"),
                plot = .x,
                device = "jpeg",
                path = "outputs/objective_1/linegraphs",
                width = 10, height = 6, dpi = 600))

# Percentage over time
plots_perc <- merged_21_l3 %>%
  group_by(us_l3name, class_21, year) %>%
  summarize(area_wc = sum(area_wc), 
            area_ha = sum(area_ha), .groups = "drop") %>%
  mutate(perc_wc = area_wc / area_ha,
         class_21 = factor(class_21)) %>%
  left_join(sens_results_21_l3, by = c("us_l3name", "class_21")) %>%
  mutate(label = paste("Sens Slope:", round(area_wc_slope, 2),
                        "\nP-value:", perc_wc_p_value)) %>%
  arrange(us_l3name) %>%
  ungroup() %>%
  group_by(us_l3name) %>%
  group_split() %>%
  set_names(map(., ~ unique(.x$us_l3name))) %>%
  map(~ ggplot(.x, aes(x = year, y = perc_wc)) +
        geom_line() +
        geom_smooth(se = TRUE, method = "loess", formula = 'y ~ x') +
        geom_text(data = .x %>% group_by(class_21) %>% 
                    summarize(x_pos = min(year), 
                              y_pos = max(perc_wc), 
                              label = first(label), 
                              .groups = "drop"), 
                  aes(x = x_pos, y = y_pos, label = label), 
                  inherit.aes = FALSE, hjust = 0, vjust = 1, size = 3) +
        facet_wrap(~ class_21, scales = "free") +
        labs(x = "Year",
             y = "Percent woody cover (%)",
             title = unique(.x$us_l3name)) +
        theme_minimal() +
        theme(legend.position = "bottom") +
        scale_y_continuous(labels = scales::percent_format()))

plots_perc %>%
  imap(~ ggsave(filename = paste0(str_replace_all(to_snake_case(.y),
                                                  "[ /]", "_"),
                                  "_perc_change.jpg"),
                plot = .x,
                device = "jpeg",
                path = "outputs/objective_1/linegraphs",
                width = 10, height = 6, dpi = 600))
```

\newpage
